name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: '50 6,21 * * *'

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.repository.name == 'HungryZJG/ZJU-Clock-In'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD}
